spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/travel_album_db

supabase:
  url: https://klbydinkovwiemketazz.supabase.co
  key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtsYnlkaW5rb3Z3aWVta2V0YXp6Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0MzE5MjIyNCwiZXhwIjoyMDU4NzY4MjI0fQ.MiLTuvIV_ScvBAkXgqphBRR1ZiM5y7a7laxmWwXD_Rg
  bucket: travel-album

jwt:
  secret: fdgfskwqubnsnjajkqknvbgKLQMNBbVSSFnjookv
  expiration: 86400000
